// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkikajhpeypnprdnxmph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZraWthamhwZXlwbnByZG54bXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDAyMTMsImV4cCI6MjA3MzUxNjIxM30.DUJ5-ZAyollfjBhJxIHZRHMj8asJuJIecvOGfApq1WQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});